In [1]:
import numpy as np
import tensorflow as tf

In [2]:
#config
inputSize = 5
outputSize = 3
batchSize = 10
testSize = 5
epochs = 400
learningRate = 0.01
seed = 123456

In [3]:
#Generation of Dataset
np.random.seed(seed)
inputArray = np.random.uniform(-5,5,(batchSize,inputSize))
weights = np.random.uniform(-5,5,(inputSize,outputSize))
outputArray = np.matmul(inputArray,weights)
inputTest = np.random.uniform(-5,5,(testSize,inputSize))
outputTest = np.matmul(inputTest,weights)

In [4]:
inputArray

array([[-3.73030167,  4.66717838, -2.39523994,  3.97236524, -1.23250284],
       [-1.63778256, -0.4862353 ,  3.40255083, -3.76897856,  0.43026202],
       [-1.26987775, -0.52003175, -3.7055932 ,  3.59878707,  3.20388363],
       [-1.47946461, -2.71112696,  2.76783751,  0.94783589, -3.62446443],
       [ 3.52899781, -2.64492522, -3.53772767,  0.89868773,  0.74011775],
       [-4.38730038,  0.90426003, -2.54650181, -1.59555063,  4.84728739],
       [ 4.19540405, -4.62228312,  3.6154929 ,  2.53568845, -0.94821245],
       [-1.56474125, -3.29082828, -1.0534099 ,  1.4166617 , -2.25407569],
       [-0.37645666,  3.71371654, -0.98868778,  1.1058827 , -3.8203287 ],
       [ 2.02184361, -0.85966335, -1.57654787,  0.95925321, -3.00135737]])

In [5]:
outputArray

array([[ 20.6768939 , -29.71868231,   5.75368214],
       [  6.86816265,   7.61094193,  18.82294379],
       [ -9.63726159, -26.41146376,  10.67733585],
       [ 31.34877658,  33.75492349,  -2.63642922],
       [-25.96702153,   2.45309506, -22.20144941],
       [-12.87306094, -44.68975321,  37.15585938],
       [  6.30264574,  48.26811154, -16.66583296],
       [ 15.11446364,  15.44104618,  -5.16952458],
       [ 14.12728662,  -3.6535083 , -17.79070525],
       [  0.04972998,  14.70611177, -26.96576621]])

In [6]:
inputTest

array([[-3.65900761,  1.30699553,  1.39568218, -0.66510215, -3.4415294 ],
       [ 3.62608983,  1.83046301, -4.14291102,  0.66102526, -3.50175146],
       [-0.22545554,  3.48938265, -3.5985558 , -1.70449185,  1.3407411 ],
       [ 1.19378493, -1.04957363,  1.72397815,  3.0998032 , -1.13000944],
       [ 0.44758747,  4.88949362,  4.84982907, -1.29618208,  0.62941932]])

In [7]:
outputTest

array([[ 29.84199788,   5.23386209,   5.87002443],
       [-14.53100643,  -0.74876053, -42.89115253],
       [-21.19204332, -35.39753098,  -0.95828189],
       [ 13.35977539,  20.35431271,  -7.6149863 ],
       [  8.10210631,  -2.77530335,  12.13804306]])

In [8]:
#initialization of NN by other random weights
nnWeights = np.random.uniform(-3,3,(inputSize,outputSize))
deltaweights = np.zeros((inputSize,outputSize))
deltainput = np.zeros((batchSize,inputSize))
deltaoutput = np.zeros((inputSize,outputSize))

In [9]:
weights

array([[-4.00263237,  2.34596222, -4.8345549 ],
       [-0.186155  , -4.04061126, -0.02693667],
       [ 3.38796274,  3.97333257,  2.32591519],
       [ 2.58724364,  0.60657183, -0.28522073],
       [-3.61231882, -4.05538867,  4.42256339]])

In [10]:
nnWeights

array([[-1.50136739,  2.85870823,  1.89927354],
       [-2.73390942, -0.54100287, -2.82068023],
       [-1.75259698,  0.7847937 ,  0.94378938],
       [-1.50410391,  2.9587439 , -2.81435983],
       [-0.86099938, -1.51593029, -1.87249127]])

In [11]:
inputArray_tf = tf.convert_to_tensor(inputArray)
weights_tf = tf.convert_to_tensor(weights)

outputArray_tf = tf.matmul(inputArray_tf,weights_tf)

nnWeights_tf = tf.convert_to_tensor(nnWeights)
deltaweights_tf = tf.convert_to_tensor(deltaweights)
deltainput_tf = tf.convert_to_tensor(deltainput)
deltaoutput_tf = tf.convert_to_tensor(deltaoutput)

In [12]:
historyTrainTF=[]
i = 1
while i <= epochs:
    with tf.Session() as session:  
        with tf.GradientTape() as tape:
            #Forward pass:
            tape.watch(nnWeights_tf)            
            nnOutput_tf = tf.matmul(inputArray_tf,nnWeights_tf)
            #print(nnOutput)
            #print(nnOutput_tf.eval())           
            lossTF = tf.reduce_mean(0.5*tf.square(nnOutput_tf - outputArray_tf))           
            historyTrainTF.append(lossTF.eval())
            #print(lossTrain)
            #print(lossTF.eval())
            tape.watch(lossTF)
            #Print Loss every 50 epochs: 
            if(i%10==0):
                print("Epoch: " + str(i) + " Loss (TF): " + "{0:.3f}".format(lossTF.eval()))

            #Backpropagate           
            deltaweights_tf = tape.gradient(lossTF,nnWeights_tf)

            #Apply optimizer
            #print(deltaweights)
            #print(deltaweights_tf.eval())
            nnWeights_tf -= deltaweights_tf*learningRate

            #Start new epoch
            i = i+1

Epoch: 10 Loss (TF): 139.093
Epoch: 20 Loss (TF): 72.917
Epoch: 30 Loss (TF): 42.783
Epoch: 40 Loss (TF): 27.811
Epoch: 50 Loss (TF): 19.624
Epoch: 60 Loss (TF): 14.704
Epoch: 70 Loss (TF): 11.493
Epoch: 80 Loss (TF): 9.251
Epoch: 90 Loss (TF): 7.602
Epoch: 100 Loss (TF): 6.339
Epoch: 110 Loss (TF): 5.343
Epoch: 120 Loss (TF): 4.540
Epoch: 130 Loss (TF): 3.881
Epoch: 140 Loss (TF): 3.334
Epoch: 150 Loss (TF): 2.875
Epoch: 160 Loss (TF): 2.487
Epoch: 170 Loss (TF): 2.157
Epoch: 180 Loss (TF): 1.875
Epoch: 190 Loss (TF): 1.632
Epoch: 200 Loss (TF): 1.424
Epoch: 210 Loss (TF): 1.244
Epoch: 220 Loss (TF): 1.088
Epoch: 230 Loss (TF): 0.953
Epoch: 240 Loss (TF): 0.835
Epoch: 250 Loss (TF): 0.732
Epoch: 260 Loss (TF): 0.643
Epoch: 270 Loss (TF): 0.565
Epoch: 280 Loss (TF): 0.497
Epoch: 290 Loss (TF): 0.437
Epoch: 300 Loss (TF): 0.384
Epoch: 310 Loss (TF): 0.338
Epoch: 320 Loss (TF): 0.298
Epoch: 330 Loss (TF): 0.262
Epoch: 340 Loss (TF): 0.231
Epoch: 350 Loss (TF): 0.204
Epoch: 360 Loss (TF):